In [2]:
import numpy as np

In [4]:
data = [[1, 2, 3], [4, 5, 6], [7, 8 , 9]]

a = np.array(data)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a.dtype

dtype('int64')

In [12]:
a = a.astype(np.float32)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [13]:
a[0][1]

2.0

In [15]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [17]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.arange(1, 13).reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
np.arange(1, 13).reshape(3, 2, 2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [25]:
np.nan * 1

nan

In [33]:
a = np.linspace(1, 10, 10)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [36]:
data  = np.arange(1, 10).reshape(3, 3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
data + data

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [43]:
# 수학적 연산
arr = np.array([1, 2, 3])
print("Original array: ", arr)

# 사칙연산
print("Addition: ", np.add(arr, 1))
print("Subtraction: ", np.subtract(arr, 1))
print("Multiplication: ", np.multiply(arr, 2))
print("Division: ", np.divide(arr, 2))

# 지수와 로그
print("Exponential: ", np.exp(arr))
print("Natural log: ", np.log(arr))
print("Base 10 log: ", np.log10(arr))

# 삼각함수
print("Sine: ", np.sin(arr))
print("Cosine: ", np.cos(arr))
print("Tangent: ", np.tan(arr))

# 통계적 연산
arr2 = np.array([1, 2, 3, 4, 5])

print("Max: ", np.max(arr2))
print("Min: ", np.min(arr2))
print("Mean: ", np.mean(arr2))
print("Median: ", np.median(arr2))
print("Variance: ", np.var(arr2))
print("Standard deviation: ", np.std(arr2))
print("Sum: ", np.sum(arr2))
print("Cumulative sum: ", np.cumsum(arr2))

# 선형대수 연산
arr3 = np.array([[1, 2], [3, 4]])

print("Matrix multiplication: ", np.dot(arr3, arr3))
print("Transpose: ", arr3.T)
print("Inverse: ", np.linalg.inv(arr3))
print("Determinant: ", np.linalg.det(arr3))

eig_val, eig_vec = np.linalg.eig(arr3)
print("Eigenvalues: ", eig_val)
print("Eigenvectors: ", eig_vec)


Original array:  [1 2 3]
Addition:  [2 3 4]
Subtraction:  [0 1 2]
Multiplication:  [2 4 6]
Division:  [0.5 1.  1.5]
Exponential:  [ 2.71828183  7.3890561  20.08553692]
Natural log:  [0.         0.69314718 1.09861229]
Base 10 log:  [0.         0.30103    0.47712125]
Sine:  [0.84147098 0.90929743 0.14112001]
Cosine:  [ 0.54030231 -0.41614684 -0.9899925 ]
Tangent:  [ 1.55740772 -2.18503986 -0.14254654]
Max:  5
Min:  1
Mean:  3.0
Median:  3.0
Variance:  2.0
Standard deviation:  1.4142135623730951
Sum:  15
Cumulative sum:  [ 1  3  6 10 15]
Matrix multiplication:  [[ 7 10]
 [15 22]]
Transpose:  [[1 3]
 [2 4]]
Inverse:  [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant:  -2.0000000000000004
Eigenvalues:  [-0.37228132  5.37228132]
Eigenvectors:  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
